### ISSUE TITLE
NPC hiding although i am at range.

### ISSUE THREAD

**Issue by HugoGamerStyle** [JitseB/NPCLib#41] opened 2019-11-03 15:14 UTC
**Describe the bug**
I can see the NPCs but sometimes they randomly despawn although I'm in range.

**NPCLib usage option**
1

**NPCLib JAR name**
npclib-plugin-2.3-SNAPSHOT.jar

**Server version**
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**To Reproduce**
Used this code:
`        NPC pirateJoeNPC = Main.getInstance().getNpcLib().createNPC(Arrays.asList("§aPirate Joe", "§7¡Ven aquí todos los días", "§7y te daré recompensas!", "§e§lCLICK"));

        pirateJoeNPC.setLocation(new Location(Bukkit.getWorld("world"), -81, 62, 0, -90, 0));
        pirateJoeNPC.setSkin(new Skin("eyJ0aW1lc3RhbXAiOjE1NjM3NTA4MzkwNzksInByb2ZpbGVJZCI6ImIwZDRiMjhiYzFkNzQ4ODlhZjBlODY2MWNlZTk2YWFiIiwicHJvZmlsZU5hbWUiOiJ4RmFpaUxlUiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTk1NjMyMDQ2YjZjMjcxNGE2YzE2Yjk3NzNjODNjNjRjNDE5NTRkMWZkMjZlZGNhNzA0NjgyYjQ4Y2FlODlkMCJ9fX0=",
                "rAlrow/DYrJPcKvuEDvI3QrgcgDiez3pCeF//Oe+3kvBHFqv/OkLRbVZwaNpQRCdbw0cGxweqItSjkNiPOu4Y7rcQLM7YcTYYrcu9UvhK/kZTvFHfmJFjPD95foI0qwIKqAkccJuTvsQlLFTKZK1QYhrTDlsRo/0HuIwVCDsEkSY0tZ991w5OMGHa+DI5YFk93RvmsG1iOyjz9Ps+lZjKSIP1iHvnY45DfeJt1ouFH5O9QJyzIQJrlv9QvcfZDYRrB6A6+M1Qhp3diI0P0wIDFsn8a4210A4LhhfKeU+Rq6aCBuxL8Ac+DR5+6adBkhh13x+0RF/AKPgMgAixUISoLAPqP27qJol8YjmpNju8njnnPeWZTSS8fd0QXeGH9lj1gfd/GyTf5+ClQNn/QFhjpmvxrrd5UuRdYedla4vDSufEJ/wMgDZ5i2IrmKGatiK0iEqpwv0ZNqvhmGhwcBtYXmyVezthWQtjIDkzwGlOI8HIxIpvlsoQ4UQOkbn/UiSlpFPlKpQ0I+3YCOHcS8V75JfrmDkjFqlC3QfEpKpFwCXBH0jNRNmg0rXVUYMq+2D/t6G2ALo8JeUJhNBfccCdrWDt8TigD5GL5j4czOHj9VQ8e6fIhrwJmQYrD1qUKFP/Ss3hQiF3r8XowoQ71ib8ji/mN5RdiqsmcbHcnPYd6k="));
        pirateJoeNPC.setItem(NPCSlot.MAINHAND, new ItemStack(Material.GOLD_INGOT));
        pirateJoeNPC.create();`
To spawn the NPC
And whenever the player joins i use this:
`        for(NPC npc : Main.getInstance().getNpcManager().getNpcInteractions().keySet()) {
            npc.show(player);
        }`
(which works cause i get to see the npcs, but they disappear randomly)

**Expected behavior**
They should not disappeaar if im in range and i havent used the .hide function.

Thanks for reading :)
If you want to join the server or any extra info add me on discord: HugoGamerStyle#0286

**Comment by JitseB** [comment] 2019-11-03 15:21
Hm. I haven't seen this NPC behavior before. I'll send you a message on Discord in a minute, see if we can reproduce it on your server.

**Comment by JitseB** [comment] 2019-11-03 16:11
Had contact with ticket owner. We were not able to reproduce the error. Could have had something to do with client side mods (SkyBlockAddon).

Closing issue for now. Will be reopened once the issue is reproduce-able.

**Closed by JitseB** 2019-11-03 16:11 UTC
Labels: bug
